apiVersion: apps/v1
kind: Deployment
metadata:
  name: kusor-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kusor-worker
  template:
    metadata:
      labels:
        app: kusor-worker
    spec:
      containers:
      - name: worker
        image: kusorregistry.azurecr.io/kusor-backend:latest
        command: ["uv", "run", "dramatiq", "--skip-logging", "--processes", "2", "--threads", "2", "run_agent_background"]
        env:
        - name: REDIS_URL
          value: "redis://:YOUR_REDIS_PASSWORD@YOUR_REDIS_HOST:6379"
        - name: SUPABASE_URL
          value: "https://YOUR_SUPABASE_PROJECT.supabase.co"
        - name: SUPABASE_SERVICE_KEY
          value: "YOUR_SUPABASE_SERVICE_ROLE_KEY"
        - name: ENV_MODE
          value: "production"
        - name: OPENAI_API_KEY
          value: "YOUR_OPENAI_API_KEY"
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 2Gi
